//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_menu()
        {
            this.admin_menu1 = new HashSet<admin_menu>();
        }
    
        public int IIDMENU { get; set; }
        public Nullable<int> IIDPAGINA { get; set; }
        public Nullable<int> IIDMODULO { get; set; }
        public Nullable<int> IIDROL { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public string MENSAJE { get; set; }
        public string CONTROLLER { get; set; }
        public string ACCION { get; set; }
        public Nullable<int> Modulop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_menu> admin_menu1 { get; set; }
        public virtual admin_menu admin_menu2 { get; set; }
    }
}
